name: file_crypt_app
description: "File crypt app"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_bloc: ^8.1.6
  theme_tailor_annotation: ^3.0.1
  go_router: ^14.6.2
  get_it: ^8.0.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  bloc: ^8.1.4
  path_provider: ^2.1.5
  responsive_framework: ^1.5.1
  path: ^1.9.0
  async: ^2.11.0
  stream_transform: ^2.1.0
  uuid: ^4.5.1
  logger: ^2.5.0
  phosphor_flutter: ^2.1.0
  drift: ^2.22.1
  drift_flutter: ^0.2.2
  flutter_staggered_grid_view: ^0.7.0
  rxdart: ^0.28.0
  sticky_headers: ^0.3.0+2
  characters: ^1.3.0
  auto_size_text: ^3.0.0
  flutter_sticky_header: ^0.7.0
  animations: ^2.0.11
  provider: ^6.1.2
  visibility_detector: ^0.4.0+2
  vibration: ^2.0.1
  image_picker: ^1.1.2
  flutter_background_service: ^5.0.10
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^11.0.0
  url_launcher: ^6.3.1
  file_picker: ^8.1.4
  marquee: ^2.3.0
  time: ^2.1.5
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  freezed: ^2.5.7
  theme_tailor: ^3.0.1
  drift_dev: ^2.22.1

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Variable.ttf
          weight: 700